name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Allows manual triggering from GitHub UI

permissions:
  contents: read # Allows reading repository contents
  pages: write # Allows deploying to GitHub Pages
  id-token: write # Required for GitHub Pages deployment

# Prevents multiple deployment workflows from running simultaneously
concurrency:
  group: "pages"
  cancel-in-progress: true

# Define environment variables available to all jobs
env:
  REPO_NAME: ${{ github.event.repository.name }} # Gets current repository name

# List of jobs to run
jobs:
  deploy:
    # Sets up the deployment environment
    environment:
      name: github-pages # Environment name
      url: ${{ steps.deployment.outputs.page_url }} # URL of deployed site

    runs-on: ubuntu-latest # Uses latest Ubuntu runner

    # Sequential steps to execute
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4 # Sets up Node.js environment
        with:
          node-version: "20"
          cache: "npm" # Caches npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_BASE_URL: "/${{ env.REPO_NAME }}/" # Sets base URL for Vite
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Uploads build output
        with:
          path: "./dist" # Path to built files

      - name: Deploy to GitHub Pages
        id: deployment # ID to reference this step
        uses: actions/deploy-pages@v4 # Deploys to GitHub Pages
